version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: ecommerce-postgres
    ports:
      - "5432:5432" # Maps PostgreSQL's default port
    environment:
      POSTGRES_DB: ecommerce         # Matches your spring.datasource.url
      POSTGRES_USER: myuser          # Matches your spring.datasource.username
      POSTGRES_PASSWORD: mypassword  # Matches your spring.datasource.password
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage for PostgreSQL

volumes:
  postgres_data: